name: 'Notation: Verify'
description: notation verify target artifact
branding:
  icon: check-circle
  color: blue
inputs:
  target_artifact_reference:
    description: 'Reference of the target artifact to be verified. <registry>/<repo>@<digest>'
    required: true
  trust_policy:
    description: 'file path of valid Notation trustpolicy.json'
    required: true
  trust_store:
    description: |
      dir of trust store following Notation trust store [spec](https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md#trust-store).
      An example:
      .github/truststore
      └── x509
          ├── ca
          │   └── <my_trust_store1>
          │       ├── <my_certificate1>
          │       └── <my_certificate2>
          └── signingAuthority
              └── <my_trust_store2>
                  ├── <my_certificate3>
                  └── <my_certificate4>
    required: true
runs:
  using: node16
  main: ../dist/verify.js