name: release-e2e-notation-plugin

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          workdir: .github/notation-plugin
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}